version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
defaults: &defaluts
 docker:
   - image: circleci/node:13.8.0

jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  test:
    <<: *defaluts
    steps:
      - run: exit 1
      - run:
        name: Upload Faile
        command: echo Catch_You
        when: on_fail
workflows:
  my_workflow:
    jobs:
      - test